# Default values for go-sample-site.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

env: dev31

ingressClassName: koderover-admin-nginx

image:
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: default-registry-secret

nameOverride: 
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080
  port2: 8000  
  preset1: $T-Service$
  presetProjectName: $T-Project$

global:
  hub: ccr.ccs.tencentyun.com/trial 

deploy:
  image:
    name: go-sample-site
    tag: 0.1.0 

github:
  knownHost:
  sshKey:
